export const dummyData = [
  {
    id: 1,
    name: "OYO",
    companyName: "OYO Pvt Ltd",
    logoUrl:
      "https://upload.wikimedia.org/wikipedia/commons/1/19/OYO_Rooms_%28logo%29.png",
    issueDate: "4th - 7th Oct 2022",
    issueSize: "3600 crores",
    priceRange: "50-60",
    minInvestQty: "100 Shares/5 Lots",
    minInvestAmount: "50,000",
    listedOn: "15 Oct 2022",
    listedPrice: "150",
    listingGainsAmt: "10",
    listingGainsPercent: "5",
  },
  {
    id: 2,
    name: "OYO",
    companyName: "OYO Pvt Ltd",
    logoUrl:
      "https://upload.wikimedia.org/wikipedia/commons/1/19/OYO_Rooms_%28logo%29.png",
    issueDate: "4th - 7th Oct 2022",
    issueSize: "3600 crores",
    priceRange: "50-60",
    minInvestQty: "100 Shares/5 Lots",
    minInvestAmount: "50,000",
    listedOn: "15 Oct 2022",
    listedPrice: "150",
    listingGainsAmt: "10",
    listingGainsPercent: "5",
  },
  {
    id: 3,
    name: "OYO",
    companyName: "OYO Pvt Ltd",
    logoUrl:
      "https://upload.wikimedia.org/wikipedia/commons/1/19/OYO_Rooms_%28logo%29.png",
    issueDate: "4th - 7th Oct 2022",
    issueSize: "3600 crores",
    priceRange: "50-60",
    minInvestQty: "100 Shares/5 Lots",
    minInvestAmount: "50,000",
    listedOn: "15 Oct 2022",
    listedPrice: "150",
    listingGainsAmt: "10",
    listingGainsPercent: "5",
  },
  {
    id: 4,
    name: "OYO",
    companyName: "OYO Pvt Ltd",
    logoUrl:
      "https://upload.wikimedia.org/wikipedia/commons/1/19/OYO_Rooms_%28logo%29.png",
    issueDate: "4th - 7th Oct 2022",
    issueSize: "3600 crores",
    priceRange: "50-60",
    minInvestQty: "100 Shares/5 Lots",
    minInvestAmount: "50,000",
    listedOn: "15 Oct 2022",
    listedPrice: "150",
    listingGainsAmt: "10",
    listingGainsPercent: "5",
  },
  {
    id: 5,
    name: "OYO",
    companyName: "OYO Pvt Ltd",
    logoUrl:
      "https://upload.wikimedia.org/wikipedia/commons/1/19/OYO_Rooms_%28logo%29.png",
    issueDate: "4th - 7th Oct 2022",
    issueSize: "3600 crores",
    priceRange: "50-60",
    minInvestQty: "100 Shares/5 Lots",
    minInvestAmount: "50,000",
    listedOn: "15 Oct 2022",
    listedPrice: "150",
    listingGainsAmt: "10",
    listingGainsPercent: "5",
  },
];
